# templates/serviceaccount.yaml
{{- if .Values.backend.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  # Use the name defined in backend.serviceAccount.name or default to a helper-generated name if not specified
  name: {{ .Values.backend.serviceAccount.name | default (printf "%s-backend-sa" (include "ts-app.fullname" .)) }}
  labels:
    {{- include "ts-app.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend # Add component label for consistency
  annotations:
    # This annotation links the SA to the Azure User Assigned Managed Identity via Workload Identity
    azure.workload.identity/client-id: {{ .Values.backend.keyVault.userAssignedIdentityClientID | quote }}
    {{- with .Values.backend.serviceAccount.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
automountServiceAccountToken: true # Required for Workload Identity token projection
{{- end }}