name: 'CD - Release backend container to ACR'
on:
    push:
        branches: [main]
        paths:
        # --- TRIGGER on changes to these files ---
        - 'backend/**/*.py'
        - 'backend/requirements.txt'
        - 'backend/Dockerfile'

        # --- IGNORE changes in this subdirectory ---
        - '!backend/tests/**'
    workflow_dispatch:
jobs:
  build_and_push_image:
    name: Build and Push Image to ACR
    permissions:
      id-token: write   # Required to get the OIDC token for Azure login
      contents: read    # Required by actions/checkout to read the repo
    uses: ./.github/workflows/reusable-build-push.yml
    with:
      dockerfile-path: 'backend/Dockerfile'
      image-name: 'backend-app'
      build-context: './backend'
      acr-name: ${{ vars.ACR_NAME }}
      environment: 'shared'
    secrets:
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}